openapi: 3.0.1
info:
  title: Action API
  version: 1.0.0
paths:
  /user/login:
    post:
      summary: Fake login
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
        - in: query
          name: email
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User logged in or already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResource'
  /actions:
    post:
      summary: Add a new action
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Action'
            examples:
              BuyAction:
                summary: Example of a buy action
                value:
                  userId: 1
                  description: "Buy 10 shares of XYZ"
                  type: BuyAutomaticAction
                  targetPrice: 100.5
                  divergenceTolerance: 0.5
                  priceIsLessThanTarget: true
                  contextId: "CTX-123"
              SellAction:
                summary: Example of a sell action
                value:
                  userId: 2
                  description: "Sell 5 shares of ABC"
                  type: SellAutomaticAction
                  targetPrice: 150.0
                  divergenceTolerance: 1.0
                  priceIsLessThanTarget: false
                  contextId: "CTX-456"
      responses:
        '201':
          description: Action created successfully
        '400':
          description: Invalid input
components:
  schemas:
    UserResource:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        balance:
          type: number
          format: double
    Action:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        description:
          type: string
        type:
          type: string
          enum: [BuyAutomaticAction, SellAutomaticAction]
        targetPrice:
          type: number
          format: float
        divergenceTolerance:
          type: number
          format: float
        priceIsLessThanTarget:
          type: boolean
        contextId:
          type: string
      required:
        - userId
        - type